coda di riproduzione
TinyTanic/music-player pull request #18
Opened 2017-06-12 14:23 UTC by gmammolo

la coda di riproduzione deve mostrare (per il momento) la lista della musica della cartella

2017-06-12 17:55 UTC, TinyTanic commented on electron.js
> +const REDUX_DEV_TOOLS = require('./config/config').REDUX_DEV_TOOLS
hai tolto config.js da git, e se il file non esistesse? al primo clone devi crearlo?

2017-06-12 17:55 UTC, TinyTanic commented on electron.js
> +    console.log(REDUX_DEV_TOOLS)
rimuovi tutti i console.log inutili

2017-06-12 17:56 UTC, TinyTanic commented on src/components/App.jsx
> +          <SideBar songs={this.props.library} dispatch={this.props.dispatch} />
in realtà non ci sarà l'intera libreria ma solo la coda di riproduzione

2017-06-12 17:57 UTC, TinyTanic commented on src/components/partials/SideBar.jsx
> +    let songs = this.props.songs
se è solo read-only allora metti const

2017-06-12 17:58 UTC, TinyTanic commented on src/components/partials/SideBar.jsx
> +            {songs.map(song => {
crea una const prima del render e poi aggiungi al jsx la variabile. diventa tutto più leggibile e maneggevole

2017-06-12 18:02 UTC, TinyTanic requested changes
Ottimo lavoro, solo riguarda le indicazioni e poi possiamo mergiare

2017-06-13 08:56 UTC, gmammolo commented on electron.js
> +const REDUX_DEV_TOOLS = require('./config/config').REDUX_DEV_TOOLS
ripristinato.
si gestirà tramite conflitto nel merge in cui si recupera la versione originale.

2017-06-13 08:59 UTC, gmammolo commented on electron.js
> +    console.log(REDUX_DEV_TOOLS)
rimosso `console.log(REDUX_DEV_TOOLS)`
il warn lo lascerei in quanto ora con il controllo fa sì che ignori la mancanza del Dev Tools
TODO: un sistema multiplex che determina se è in esecuzione una versione produzione o development

2017-06-13 09:00 UTC, gmammolo commented on src/components/App.jsx
> +          <SideBar songs={this.props.library} dispatch={this.props.dispatch} />
penso che l'utente si aspetti che aggiungendo della musica nel lettore questa vada automaticamente anche nella coda di riproduzione (molti lettori funzionano cosi)
In ogni caso per il momento può andare come stub

2017-06-13 09:30 UTC, gmammolo commented on electron.js
> +const REDUX_DEV_TOOLS = require('./config/config').REDUX_DEV_TOOLS
per evitare che venga modificato con altre configurazioni è stato messo nella lista ignorati
`git update-index --skip-worktree config/congi.js`
per visualizzare la lista:
`git ls-files -v . | grep ^S`
mentre per ripristinarlo:
`git update-index --no-skip-worktree config/congi.js`

2017-06-13 10:47 UTC, TinyTanic approved these changes

2017-06-13 10:47 UTC, merged

2017-06-13 10:48 UTC, TinyTanic commented
FIX #17